My_Profile/urls.py
from django.urls import path
from .views import homepage, contact, aboutme, skills, new_page

app_name = "Story_4"

urlpatterns = [
	path('', homepage, name="homepage"),
     path('about', aboutme, name="aboutme"),
     path('skill', skills, name="skills"),
     path('contact', contact, name="contact"),
     path('new', new_page, name="new_page")
]

Story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Story_4/', include("My_Profile.urls"))
]

My_Profile/models.py
from django.db import models

# Create your models here.

My_Profile/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'homepage.html', {})

def contact(request):
    return render(request, 'contact.html', {})

def aboutme(request):
    return render(request, 'aboutme.html', {})

def skills(request):
    return render(request, 'skills.html', {})

def new_page(request):
    return render(request, 'new_page.html', {})

My_Profile/templates/aboutme.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div id="aboutMe" class="offset" style="min-height: 100vh">
    <div class="row text-center">
        <div class="col-5">
            <img class="foto" alt="fotoku" src="{% static 'profile.jpg' %}">
        </div>
        <div class="col-7">
            <div class="caption1">
                <h1>About Me</h1>
                <p>My name is Aan Nur Wahidi, I am Computer Science undergraduate of Universitas Indonesia</p>
                <hr/>
            </div>
        </div>
    </div>
    <div class="hobbies text-align-center">
        <div class="col-5">
            <h1>Hobbies</h1>
        </div>
        <div class="isi">
            <div class="col-2">
                <ul class="icon" style="list-style: none;">
                    <li>
                        <i class="fas fa-music fa-2x"></i>
                    </li>
                    <li>
                        <i class="fas fa-gamepad fa-2x"></i>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-5">
            <ul class="caption2" style="list-style: none;">
                <li>
                    Listening Music
                </li>
                <li>
                    Playing Games
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock body %}

My_Profile/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Profile</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
     integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body data-spy="scroll" data-target="#navbarResponsive">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Story_4:homepage' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Story_4:aboutme' %}">About Me</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Story_4:skills' %}">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Story_4:contact' %}">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block body %}
    {% endblock body %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/df41bae017.js" crossorigin="anonymous"></script>
<script src="https://code.iconify.design/1/1.0.3/iconify.min.js"></script>
</body>
</html>

My_Profile/templates/contact.html
{% extends 'base.html' %}

{% block body %}

<div id="contact" class="offset" style="min-height: 100vh">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h1>Contact</h1>
        </div>
        <div class="col-md-2  text-center">
            <a href="https://www.facebook.com/aan.nurwahidi.1"><i class="fab fa-facebook-square fa-5x"></i></a>
        </div>
        <div class="col-md-2  text-center">
            <a href="mailto:<aan>aannurwahidi17@gmail.com?Subject=Hello!!"><i class="fas fa-envelope fa-5x"></i></a>
        </div>
        <div class="col-md-2  text-center">
            <a href="https://www.instagram.com/aannurwahidi7"><i class="fab fa-instagram fa-5x"></i></a>
        </div>
        <div class="col-md-2  text-center">
            <a href="https://api.whatsapp.com/send?phone=6282122693195&text=&source=&data="><i class="fab fa-whatsapp fa-5x"></i></a>
        </div>
        <hr/>
    </div>
    <div class="new text-center">
        <a class="btn btn-outline-light btn-lg" href="{% url 'Story_4:new_page' %}">To my secret page</a>
    </div>
</div>

{% endblock body %}

My_Profile/templates/homepage.html
{% extends 'base.html' %}

{% block body %}
<div id="home">
    <div class="landing">
        <div class="home-wrap">
            <div class="home-inner">
            </div>
        </div>
    </div>

    <div class="caption text-center">
        <h1>Hello, I'm Aan</h1>
        <hr/>
        <h1>Computer Science of Universitas Indonesia</h1>
        <a href="{% url 'Story_4:homepage' %}"><i class="fas fa-chevron-down fa-4x"></i></a>
    </div>
</div>
{% endblock body %}

My_Profile/templates/new_page.html
{% extends 'base.html' %}

{% block body %}
<div id="new_page" style="min-height = 100vh">
    <h1>There's nothing important here</h1>
</div>
{% endblock body %}

My_Profile/templates/skills.html
{% extends 'base.html' %}

{% block body %}

<div id="skills" class="offset">   
    <div class="fixed-background">
        <div class="dark" style="min-height: 100vh">
        <div class="col-md-12 text-center">
            <h1>Skills</h1>
        </div>
        <div class="skill1">
            <div class="col-2">
                <iconify-icon data-icon="logos:python"></iconify-icon>
            </div>
            <div class="col-3">
                <p>Python</p>
            </div>
            <div class="col-7">
                <div class="progress">
                    <div class="progress-bar bg-secondary" style="width:65%"></div>
                </div>
            </div>
            <hr/>
        </div>
        <div class="skill2">
            <div class="col-2">
                <iconify-icon data-icon="logos-java"></iconify-icon>
            </div>
            <div class="col-3">
                <p>Java</p>
            </div>
            <div class="col-7">
                <div class="progress">
                    <div class="progress-bar bg-secondary" style="width:73%"></div>
                </div>
            </div>
            <hr/>
        </div>
        <div class="skill3">
            <div class="col-2">
                <iconify-icon data-icon="logos:html-5"></iconify-icon>
            </div>
            <div class="col-3">
                <p>HTML</p>
            </div>
            <div class="col-7">
                <div class="progress">
                    <div class="progress-bar bg-secondary" style="width:65%"></div>
                </div>
            </div>
            <hr/>
        </div>
    </div>
        <div class="fixed-wrap">
            <div class="fixed">
            </div>
        </div>
    </div>
</div>

<div class="content text-center"> 
</div>

{% endblock body %}